# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julien Duroure
email: contact@julienduroure.com
description: Julien Duroure - Rigging - Animation - Formation - Développement
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://julienduroure.com" # the base hostname & protocol for your site
twitter_username: julienduroure
github_username:  julienduroure

# Build settings
markdown: kramdown

exclude: [Gemfile, Gemfile.lock]
